name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install packages
      run: npm ci
    - name: Build nodejs project
      run: npm run build
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sports2000:$(date +%s)
    - name: Log into registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USER }} --password-stdin
