name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: npm ci
    - name: Build nodejs project
      run: npm run build
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sports2000:$(date +%s)
